# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39eb8c0607be3e4b84ddc0e31321b8b39e76af223c20d4f90363002a837bb5df986f07255ec913bfa1cf9df420284c9b2719d2b36e295cbe59e02a1fa1927dfe

test:
  secret_key_base: 43b45050c3a408d0f9ded4eba39f5cbb590eb77edaedaa76041e486520f0f661583b6082ac6d2546882aa085e585cd1654cb142f14a2ee7b0555f502bb4c6122

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
